name: Changesets
on:
  push:
    branches:
      - main
env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store
jobs:
  version:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    permissions:
      contents: write
      checks: read
      issues: read
      packages: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@juicyarts'
      - name: install pnpm
        run: npm i pnpm@latest -g
      - name: setup pnpm config
        run: |
          pnpm config set store-dir $PNPM_CACHE_FOLDER
          pnpm config set "//registry.npmjs.org/:_authToken" "${NODE_AUTH_TOKEN}"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: install dependencies
        run: pnpm install
      - name: create versions
        uses: changesets/action@v1
        id: changesets
        with:
          version: pnpm ci:version
          publish: pnpm ci:publish
          commit: 'chore: update versions'
          title: 'chore: update versions'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
