name: Test

on: [push]

env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store

jobs:
  lintAndTest:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
      - name: Prepare repository
        run: git fetch --unshallow --tags

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '18.2'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@juicyarts'

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.32.2

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: setup pnpm config
        run: |
          pnpm config set store-dir $PNPM_CACHE_FOLDER
          pnpm config set "//npm.pkg.github.com/:_authToken" "${NODE_AUTH_TOKEN}"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: pnpm install

      - name: Test
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pnpm run test:ci

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.36
        if: always()
        with:
          files: 'reports/**/*.xml'
